package com.github.jeffw12345.draughts.models.messaging;

public enum ServerResponseType {
    ASSIGN_RED_COLOUR, //TODO - Plumbing
    ASSIGN_WHITE_COLOUR, //TODO - Plumbing
    UPDATE_BOARD_SAME_TURN,
    UPDATE_BOARD_CHANGE_OF_TURN,
    DECLINE_MOVE,
    INFORM_RED_IS_WINNER,
    INFORM_WHITE_IS_WINNER,
    INFORM_OF_DRAW_ACCEPTED,
    INFORM_OF_STALEMATE,
    INFORM_OTHER_PLAYER_RESIGNED,
    INFORM_DRAW_OFFER_MADE,
    INFORM_OTHER_CLIENT_CLOSED_WINDOW,
    INFORM_SHUT_DOWN
}
